### ISSUE TITLE
tilespec documentation and maskUrl

### ISSUE THREAD

**Issue by djkapner** [fcollman/render-python#101]
I'm starting to work with masks for crack handling, and there's something about the tilespec class I don't understand. The imageUrl and maskUrl are top-level fields of the class, but, in reality, I never access these top-level fields.
For example, I never look here:
```mytilespec.imageUrl```
but instead here:
```mytilespec.ip.mipMapLevels[0].imageUrl```
similarly, maskUrls seem to go into the image pyramid also, so, why are these top-level fields here:
https://github.com/fcollman/render-python/blob/221e73e1cf68bbc7e02cd4f6bea5cd963329e925/renderapi/tilespec.py#L31-L38

more of a question than an issue

**Comment by fcollman** [comment]
yeah this is a deprecation issue.. when i first wrote this, i didn't really care about mipmaplevels (because i was young and stupid) so i made it a top level field, in order to facilitate easy construction and manipulation in less verbose terms.  We then added the more general mipmaplevels... we also have a branch which implements the mipmaplevels in a more elegant dictionary method, but this will be a breaking change (as would removing the imageUrl from the top level).  We are collecting such changes for a 2.0 release... we should probably add deprecation warnings to this effect.

**Comment by djkapner** [comment]
ok, understood
